### ISSUE TITLE
similar_posts: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. 

### ISSUE THREAD

**Issue by everton3x** [davidlesieur/similar_posts#1]
Hello!

I'm using the similar_posts plugin for Pelican and while doing html make I'm getting the following message:

> FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

I tried to locate the source, but since I'm a beginner in Python, I could not.

can anybody help me? If the correction is easy, I can do it and send a PR.

**Comment by davidlesieur** [comment]
Thanks for posting this project's first issue. ;-)
